underlay:
  ospf:
    routerid: Loopback0
    process: underlay
    area: 0
    cost: 1
  pim:
    interface: Loopback254
    address: 10.254.254.254
    mask: 30
    description: pim_rp_anycast
    grouplist: 233.0.0.0/24
  role: leaf
  loopbacks:
    - interface: Loopback0
      ipaddress: 10.10.10.5
      mask: 32
      description: loopback_underlay
  nve_loopbacks:
    - interface: Loopback1
      ipaddress: 10.200.200.5
      mask: 32
      description: loopback_underlay
  interfaces:
    - interface: Eth1/54
      description: to_n9k-spine-1_ethernet2/12
      ipaddress: 10.1.1.7
      mask: 31
      mtu: 9216
