underlay:
  ospf:
    routerid: Loopback0
    process: underlay
    area: 0
    cost: 1
  pim:
    interface: Loopback254
    address: 10.254.254.254
    mask: 32
    description: pim_rp_anycast
    grouplist: 233.2.0.0/24
  role: leaf
  loopbacks:
    - interface: Loopback0
      ipaddress: 10.20.10.2
      mask: 32
      description: loopback_underlay
  nve_loopbacks:
    - interface: Loopback1
      ipaddress: 10.200.200.2
      mask: 32
      description: loopback_underlay
  interfaces:
    - interface: Eth1/49
      description: to_n9k-spine-2_ethernet1/31
      ipaddress: 10.2.1.2
      mask: 30
      mtu: 9216
