- name: Configure VLAN
  hosts: [leaf]
  connection: local
  gather_facts: no
  roles:
    - common
  tasks:
    - name: Create VLAN
      nxos_vlan:
        vlan_id: 665
        admin_state: up
        name: test665
        provider: "{{ nxapi }}"
