---
- name: Generate common variables
  hosts: [spine,leaf,bleaf]
  connection: local
  gather_facts: no
  vars:
    generate_p2p:
      nbr_networks: 10
      network_size: 30
      network_pool: 10.1.1.0/24
    generate_rid:
      nbr_networks: 6
      network_size: 32
      network_pool: 10.10.10.0/24
  roles:
    - generate_p2p_subnets
    - generate_rid_subnets

- name: Generate Leaf variables
  hosts: [leaf,bleaf]
  connection: local
  gather_facts: no
  vars:
    generate_vtep:
      nbr_networks: 6
      network_size: 32
      network_pool: 10.200.200.0/24
  roles:
    - generate_vtep_subnets

- name: Generate Underlay variables
  hosts: [spine,leaf,bleaf]
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  vars:
    ospf:
      routerid: Loopback0
      process: underlay
      area: 0
      cost: 1
    pim:
      interface: Loopback254
      address: 10.254.254.254
      mask: 30
      description: pim_rp_anycast
      grouplist: 233.0.0.0/24 
  roles:
    - generate_underlay_variables

- name: Generate Overlay variables
  hosts: [spine,leaf,bleaf]
  connection: local
  gather_facts: no
  pre_tasks:
    - include_vars: "{{ topology_file }}"
  vars:
    bgp:
      asn: 65500
      routerid: Loopback0
      updatesource: Loopback0
    overlay:
      anycastgwmac: "aaaa.aaaa.aaaa"
      nvesourceifx: Loopback1
      nveholddown: 60
  roles:
    - generate_overlay_variables
